- src: https://github.com/egi-qc/ansible-umd
  version: master
  name: umd

- src: https://github.com/egi-qc/ansible-grid-security
  version: master
  name: grid-security

- src: https://github.com/egi-qc/ansible-bdii
  version: master
  name: bdii
